# Usar imagen oficial de nginx para servir Laravel
FROM nginx:1.27.3-alpine3.20

# Copiar configuración personalizada de nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]